language: node_js
node_js:
  - "10.5.0"
script:
  - npm install
  - npm run build
  - npm run export
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN